# Generated by Django 4.0.6 on 2022-07-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField()),
                ('published_on', models.DateTimeField()),
                ('thumbnail_url', models.URLField(help_text='URL of the thumbnail', max_length=255)),
                ('url', models.URLField(help_text='URL of the video', max_length=255)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-published_on'],
            },
        ),
    ]
